### PR TITLE
WIP - Bug Fixes

### PR DESCRIPTION
**Pull request by gavinhenderson**
- [x] Sometimes input is ignored
- [x] The wrong letter is highlighted
- [x] Full screen view is weird with the new keyboard
- [x] Make the UI for keyboard presses cleaner
- [x] Update about page
- [x] Make settings buttons clearer
- [x] Persist settings
- [x] Currently gets stuck after video
- [x] Device testing
- [x] Add a restart button
- [ ] Fix screen size stuff

### CODE REVIEW

**Comment by gavinhenderson** [comment]
@willwade Can you check over the preview to make sure its all okay and works as expected?

I did some quite a lot of testing including cross platform but would appreciate a quick double check to see if I missed anything obvious

**Comment by willwade** [comment]
Will do!

**Comment by willwade** [comment]
Is this PR on netlify?

**Comment by gavinhenderson** [comment]
@willwade Yup https://deploy-preview-19--morse-learn.netlify.app/

**Comment by willwade** [comment]
I'm on mobile so take with a pinch of salt... but it seems to be hard to do characters of more than one element long eg .- quickly. It's as though there needs to be a delay between you tapping on the characters dot  then dash. Are you finding that?

**Comment by willwade** [comment]
Re: keyboard characters to support. I think we need to support space and enter. This is a quick list of Bluetooth switch boxes and keys they send fir reference https://gist.github.com/willwade/1dcef66ef5399a58bacedda88961dedd - I guess we could remove the slash as a character?

**Comment by willwade** [comment]
Re: wrong key highlighting. So do you think it's what's expected to highlight what the last letter was? I'm now starting to wonder if that's what a user _expects_ that UI to be doing?

**Comment by gavinhenderson** [comment]
>  I think we need to support space and enter.

100% makes total sense given that input list. I've added that now 👍 

> I'm on mobile so take with a pinch of salt... but it seems to be hard to do characters of more than one element long eg .- quickly. It's as though there needs to be a delay between you tapping on the characters dot then dash. Are you finding that?

Oh yeah good spot. Luckily the key board input seems fine but yeah not sure why the buttons do that 🤔  I had a quick dig, its to do with browser event handlers touch vs click. Seems fixable but requires some thought. For me i only notice it on mobile when im going really really fast so I was thinking that we don't need to block this PR and I can create a new issue for this? Thoughts?

**Comment by willwade** [comment]
Yeah - don't block this PR. Do it as another issue.. 

Theres something dodgy going on in Safari and Edge.. on my Mac. Its as though the screensize isn't right..

Screenshot 2021-04-14 at 10 39 15

**Comment by michaelritson** [comment]
To add to Will's comment, the bottom section of the screen is also cut off in Firefox on this Windows laptop:
MorseLearn_Firefox Windows

**Comment by gavinhenderson** [comment]
Yeah thats a problem.

Going to have to do some aspect ratio calculations, but shouldnt be to bad

**Pull request merged**
