### PR TITLE
add preload loading spinner with SpinKit

### PR DESCRIPTION
**Pull request by supertommy**
For Issue 1 here: https://gist.github.com/willwade/1a568abaf332dcee9498a91e2e58db2a

added a spinner using SpinKit that shows up when `preload()` starts and then goes away when `create()` is called.

Let me know if this implementation does not work for you!

### CODE REVIEW

**Comment by supertommy** [comment]
PR close was accidental 😭

**Comment by supertommy** [comment]
@willwade just in case you aren't notified of PRs

**Comment by willwade** [comment]
Awesome! Im not seeing anything though - I'm on Safari/Firefox on MacOS - here's the build: https://deploy-preview-2--morse-learn.netlify.com

**Comment by supertommy** [comment]
@willwade hmm, maybe there's something I missed with the css build step? I added this to `style.scss` https://github.com/supertommy/morse-learn/blob/286dd35e10c8ee4ae244325004fc47b53fcd88b8/styles/style.scss#L7

I did have trouble running `npm run start` so I used `npm run sass` and then `npm run serve` to test.

**Comment by supertommy** [comment]
@willwade ok, so I just checked the console and it is not loading the spinkit.css file at: https://deploy-preview-2--morse-learn.netlify.com/node_modules/spinkit/spinkit.css

I will try to understand the build process some more but let me know if you see exactly what I missed 😄

**Comment by willwade** [comment]
Ahh ok - let me look into that..

This is our build command: npm install && npm rebuild node-sass && npm run browserify && npm run sass
I’ll see whats going on locally...

**Comment by supertommy** [comment]
@willwade I think I fixed it! I can see the loader in the build: https://deploy-preview-2--morse-learn.netlify.com

I was expecting sass to inline the css I imported but I guess it only does so when I do not specify an extension

**Comment by willwade** [comment]
Awesome! https://5e7e1a8b9243a10008d9c831--morse-learn.netlify.com

**Pull request merged**
